# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE ##Recusrive Feature elimination
from sklearn.svm import SVR ## svm -> super vector machine SVR -> para llevar a cabo el modelo lineal
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("datasets/ads/Advertising.csv")

In [3]:
feacture_cols = ["TV", "Radio", "Newspaper"]

In [4]:
x = data[feacture_cols] ##Variables candidatas a ser variables predisoras
y = data["Sales"]##La variable que voy a predecir

In [5]:
estimator = SVR(kernel="linear")##Modelo lineal
selector = RFE(estimator, 2, step=1)##Estimar dos variables predictivas, step-> hacerlo a un paso
selector = selector.fit(x,y)

In [6]:
selector.support_ ##Lista de variables candidatas que quedan, son TV, Radio y descartada Newspaper

array([ True,  True, False])

In [7]:
selector.ranking_ ##Las variables se ordenan según su signifficancia hacia el modelo, las 1 son las más importantes

array([1, 1, 2])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
x_pred = x[["TV", "Radio"]] ##Variables predictoras

In [10]:
lm = LinearRegression()
lm.fit(x_pred, y)##Ajusta las variables predictoras para la columna de ventas "Y"

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
lm.intercept_ ##Donde intercepta

2.921099912405138

In [12]:
lm.coef_

array([0.04575482, 0.18799423])

In [13]:
lm.score(x_pred, y) ##Valor de R² Rcuadrado

0.8971942610828956