# El método de k-means


In [2]:
import numpy as np

In [5]:
data = np.random.random(90).reshape(30,3) # 30 filas por 3 columnas
data

array([[0.07686483, 0.51422725, 0.99467043],
       [0.63841531, 0.76687266, 0.95754541],
       [0.02165067, 0.69785797, 0.52614654],
       [0.71801196, 0.3857519 , 0.8682573 ],
       [0.16587388, 0.14736123, 0.73477528],
       [0.10851905, 0.56914933, 0.59873535],
       [0.98644953, 0.95871797, 0.11726454],
       [0.25772069, 0.52994988, 0.98462739],
       [0.83135588, 0.92129945, 0.5133856 ],
       [0.10117144, 0.68897328, 0.78105531],
       [0.93618968, 0.05987685, 0.70819364],
       [0.47358134, 0.65886627, 0.8195501 ],
       [0.81808339, 0.15197041, 0.48364023],
       [0.19326392, 0.38331896, 0.09689997],
       [0.7663356 , 0.40324688, 0.26030547],
       [0.97742371, 0.33696693, 0.81157541],
       [0.70962274, 0.58420413, 0.3953894 ],
       [0.17378145, 0.33507851, 0.59555576],
       [0.71990711, 0.89784953, 0.90822027],
       [0.35556034, 0.95467944, 0.82404893],
       [0.8673558 , 0.06029675, 0.64614369],
       [0.9357965 , 0.15616486, 0.50342041],
       [0.

In [6]:
c1= np.random.choice(range(len(data)))
c2= np.random.choice(range(len(data)))
clust_centers=np.vstack([data[c1], data[c2]])
clust_centers

array([[0.17378145, 0.33507851, 0.59555576],
       [0.71990711, 0.89784953, 0.90822027]])

In [7]:
from scipy.cluster.vq import vq

In [8]:
vq(data, clust_centers)

(array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 0], dtype=int32),
 array([0.44808439, 0.16195315, 0.39946258, 0.51365807, 0.23384264,
        0.24301943, 0.83687562, 0.44316744, 0.41093205, 0.40610812,
        0.81834562, 0.35447396, 0.67910136, 0.50136245, 0.68422226,
        0.62469538, 0.60122767, 0.        , 0.        , 0.37823672,
        0.74773627, 0.78814082, 0.24469705, 0.22734053, 0.27503587,
        0.40642628, 0.52935264, 0.5353668 , 0.17461404, 0.57322377]))

In [9]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, clust_centers) #Arroja información de los varicentros

(array([[0.34962809, 0.38735467, 0.56277985],
        [0.70959083, 0.75069437, 0.6829962 ]]), 0.4170884305825048)

In [12]:
kmeans(data, 2)

(array([[0.18657909, 0.51695826, 0.6114622 ],
        [0.80064728, 0.54842283, 0.61027059]]), 0.38202043023900883)